### ISSUE TITLE
Cannot load IDE

### ISSUE THREAD

**Issue by marklee45** [JuiceMind/JuiceMind#475] opened 2024-09-19 14:34 UTC
https://play.juicemind.com/dashboard/teams/3qAf4LwSgbCbwVQSdPKh/item/e38f4f6f-9307-4ed9-8b85-c633c0ff4d12

![Image](https://github.com/user-attachments/assets/9393660e-7242-4c4f-af8c-8b5289267f87)

**Comment by juicemind-dev** [comment] 2024-09-19 15:55
Confirmed that this is due to the transfer not working because this only had 0 byte file inside of project folder resulting in folder not transferring.

**Comment by marklee45** [comment] 2024-09-20 02:22
The above case is now working properly.

**Closed** 2024-09-24 03:07 UTC
