### ISSUE TITLE
Create starter code generating error

### ISSUE THREAD

**Issue by marklee45** [JuiceMind/JuiceMind#479] opened 2024-09-19 15:51 UTC
https://play.juicemind.com/dashboard/teams/D6SvmHvnMhaBuUwN7wdI/item/1aae2e8d-d88c-4dcf-a2c5-6c185a72d5d5

![Image](https://github.com/user-attachments/assets/7d916b47-c2b0-4144-ad56-b99f3a29cb87)

**Comment by juicemind-dev** [comment] 2024-09-19 15:59
Confirmed that this is due to the transfer not working because this only had 0 byte file inside of project folder resulting in folder not transferring.

**Comment by marklee45** [comment] 2024-09-20 02:54
above example is now fixed

**Closed** 2024-09-24 03:07 UTC
